<?php

    /*
            - Session introduction (part1) :
                . Session is stored in the server
                . Session store only a user key in cookie to know its you 
                . Key are generated by php engine so its almost impossible to gess
                . Yoy need to add it before any output 
    */

    echo "<h1> Session introdction (part1) : </h1>";
    print "<hr>";
    print "<br>";

    session_start();
    $_SESSION["id"] = 100;
    $_SESSION["name"] = "mouhamed";
    $_SESSION["age"] = 19;

    echo "<pre>";
        print_r($_SESSION);
    echo "</pre>";

    echo '<a href="test.php">TestFile</a>';
