<?php

    /*
            - Session introduction (part1) :
                . Session is stored in the server
                . Session store only a user key in cookie to know its you 
                . Key are generated by php engine so its almost impossible to gess
                . Yoy need to add it before any output 
    */
    session_start();
    $_SESSION["id"] = 100;
    $_SESSION["name"] = "mouhamed";
    $_SESSION["age"] = 19;

    echo "<pre>";
        print_r($_SESSION);
    echo "</pre>";

    print "<br>";

    $_SESSION["name"] = "Mouhamed";

    // Views number : 
    if (isset($_SESSION["views"])) {
        $_SESSION["views"]++;
    }
    else {
        $_SESSION["views"] = 1;
    }
    echo "hello "  . $_SESSION['name'] . " Your page views are : " . $_SESSION["views"] ;  

    print "<br>";
    print "<br>";

    $_SESSION["name"] = "Talibi";
    // session_unset();  // -> it just unset the session
    // session_destroy(); // -> it delete the session 
    if ($_SERVER['REQUEST_METHOD'] === "POST") {
        if ($_POST['user'] === "Talibi") {
            $_SESSION['username'] = "mouhamed";
            $_SESSION['id'] = 100;
        }
    } 

    echo "<pre>";
        print_r($_SESSION);
    echo "</pre>";

    if (isset($_SESSION['username'])) {
        echo "Welcome " . $_SESSION['username'];
    }